### ISSUE TITLE
acceptConfirmationForObject

### ISSUE THREAD

**Issue by Vankxr** [DoctorMcKay/node-steamcommunity#147]
I've been digging the code and I realised this function calls steam time servers to get the time offset everytime it is called.
Isn't it easier and more efficient to query the time offset once at the start and only do it when something goes bad?
Or ask for a conf and allow key so that users can generate them themselves like the other methods.

I think this would speed up a little bit confirming confirmations (XD)

**Comment by DoctorMcKay** [comment]
:+1: Good idea.

Unfortunately, it isn't very feasible to allow users to provide their own keys and times, since two keys are needed (one to load the listing, and another to accept the confirmation). Would require two keys and times to be provided, and they must both be unused (well, not necessarily, as the `conf` one can be reused).

**Comment by Vankxr** [comment]
Hmm. If there is a way to know when steam returns an error meaning the key is wrong We could do ehat i said (query the offset at start and re-query if steam returns wrong key).

Maybe a 403 http error on the request?
