### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by NikKOo31** [DoctorMcKay/node-steamcommunity#176]
Hello, I got this in console last night. I can't say much about it, since I'm pretty new to js.

![screenshot_1](https://user-images.githubusercontent.com/30965838/29245163-c783098c-7fa7-11e7-93a2-ace59cbdfc3f.png)

Obviously, I can't reproduce it. It happened while I wasn't online, and the account I was using for testing doesn't have any friends that chats with it, so I really don't know what triggered the event.

**Comment by Aareksio** [comment]
Seems like `_chatUpdatePersona` was called (rather got response) after `chatLogoff`. `chatLogoff` deletes `SteamCommunity.chatFriends`, that's why the error implies it's `undefined`.

Without debug log it's hard to say what exactly have happened. Are you using `chatLogoff`, any method prefixed with underscore (`_`)  or modifing `SteamCommunity` properties manually in your code?

**Comment by NikKOo31** [comment]
Hi Aareksio, thanks for the response!
I do use a call to `chatLogoff()`, and also `gamesPlayed([])`. And they are called in that order before using `webLogOn()` to refresh the session at intervals of 2 hours. I've had the bot running that way since a few weeks, but it's the first time that I see this error. May it be caused by my crappy internet connection?

**Comment by DoctorMcKay** [comment]
Was probably the result of a request being outstanding when you logged off of chat. This should be fixed in 3.32.1.
