### ISSUE TITLE
Are you for real???

### ISSUE THREAD

**Issue by mrspartak** [DoctorMcKay/node-steamcommunity#177]
What the fuck is this?
https://github.com/DoctorMcKay/node-steamcommunity/commit/3045a5d0ccb2bf34f18355de6dba38e606ef35a6

Remove this shit

**Comment by Rob--** [comment]
Calm down, it's anonymous and you can opt out.

**Comment by mrspartak** [comment]
Why is this by default enabled?

**Comment by andrewda** [comment]
So that @DoctorMcKay can get useful statistic and improve the module?

Opting out is super easy if you read the documentation: https://github.com/DoctorMcKay/node-stats-reporter#opting-out -- nothing to get riled up about.

**Comment by andrewda** [comment]
Just to note, nothing personal _at all_ is collected -- not your trade offers, not your friends list, not the messages you send. Nothing. Again, all the information that is collected can be found in the documentation. Don't want to share your CPU model or OS? Cool. Opt-out.

**Comment by DoctorMcKay** [comment]
Since it seems you aren't interested in using my (free, as in beer and speech) code, here's how you can remove it:

`npm remove steamcommunity`

**Comment by mrspartak** [comment]
So I saw no answer, why the hell do you collect all this data. 

> Since it seems you aren't interested in using my (free, as in beer and speech) code, here's how you can remove it:
>npm remove steamcommunity

Stupid answer, from where it seems so? Why is data collecting enabled by default?

**Comment by DoctorMcKay** [comment]
Having information about the users of my software allows me to make informed decisions regarding things like which Node.js versions I should support and the like. If you are vehemently opposed to my knowing whether your OS is 32- or 64-bit, you can either opt-out or not use the code.

It's enabled by default because otherwise it would be useless.

**Comment by scholtzm** [comment]
To be fair, I'm not a big fan of opt-out analytics either.

It *is* mentioned in the README and I understand that it can be fairly useful to know which versions of node should be supported, but lots of other far more popular packages don't do this and they have to deal with the same problem.

**Comment by andrewda** [comment]
@scholtzm Yea, same sentiment here. I would leave it enabled if it reported stats much less frequently (every 6/12 hours, maybe?) instead of every hour. Even if it is just a single request, still seems unnecessarily often to me (my CPU, OS, and Node version aren't going to change every hour, and, correct me if I'm wrong, but I feel like RAM and uptime reports aren't worthy of such frequent requests).

**Comment by Kondax** [comment]
@andrewda I agree with you however there was an issue uncovered a few months ago regarding languages. In the trade offer library you can - as you're aware - set a language to fetch item descriptions. These descriptions are saved in-memory for the duration of runtime. If you're performing a lot of trades this can and will bloat the memory usage quickly.

McKay said before that he was going to see into changing this but I guess he never got around to it / or forgot. Issues like that are the only reason I see fit for reporting at such a short interval.

I don't personally have analytics enabled and it is annoying having to opt-out. A lot of the time I'll forget about them which will cause me to leave them running. There (in my opinion) really isn't any reason to be sending analytical data so frequently for a module this small (reason above isn't really any justification) and McKay even said himself that he hasn't really looked at the data.

**Comment by jsieler** [comment]
I'm not a fan of anonymous statistics reporting, and without even explicit question if i want to send it.
If you want to opt-out, just add somewhere at the start of your script:
`global._mckay_statistics_opt_out = true;`

**Comment by jsieler** [comment]
One thing i don't really understand, what is the reason to send this stats that frequent? One time on start isn't enough?

NodeJS version will not change while running.
System OS/Version will not change during run either.

So, what's the reason?

**Comment by titanco** [comment]
I totally agree with you:
> what is the reason to send this stats that frequent? One time on start isn't enough?

**Comment by Aareksio** [comment]
Does sending a few bytes of data really matter that much to you? You wouldn't notice performance change if it ticked 100 times more often. Not a reason to yell about. As the code is open (you can always inspect it on disk) and anonymous, shouldn't be a problem - I guess most of you read this comment on Windows using Chrome, being tracked by GH and Google Analytics, possibly having Facebook tab and some app open in the background, that also sends stats (if only) outside.

**Comment by mrspartak** [comment]
I know many users, that use plugins like ghostery. Noone wants to be watched. I think it is time to write such plugin for node, to track all requsts, that it send besides your written ones.

**Comment by mrspartak** [comment]
So just use this method, to black/white list outgoing requests.

https://gist.github.com/mrspartak/749f9aedb12ea0c8022d25c4f94847f6

**Comment by andrewda** [comment]
I mean, again, the equivalent of ghostery here would be simply setting an environment variable... Hands down much easier than installing anything.

As a user of `node-steamcommunity` or any other of @DoctorMcKay's Steam modules, I'm not sure why you can't understand that these are here to _help_ you and every other user. If something goes terribly wrong and the module breaks, these statistics reports will be incredibly helpful so that the issue can be solved quickly.

Quick suggestion for @DoctorMcKay, though: Would it be possible to prompt the user upon first running the module whether they'd like to send reports? Then you'd be able to save their preference to something like `~/.mckay_statistics` so it's persistent throughout all future apps.

**Comment by DoctorMcKay** [comment]
It would be nice to be able to prompt the user, but without intimately knowing the environment in which it's running, that will likely just end up hanging an unattended terminal.

I could probably at least add some output in `npm install`.
