### ISSUE TITLE
getWebApiOauthToken won't work for (partially) limited accounts

### ISSUE THREAD

**Issue by scholtzm** [DoctorMcKay/node-steamcommunity#18]
My bot account has been *partially* limited for a while now - I can't use the web chat or sell stuff on the market. Features such as friend invites, trade requests etc. work just fine though. I can also authorize the account using the mobile app.

I have read somewhere that this is caused by not buying anything from Steam for 1 year.

Because of this limitation, the web chat window **doesn't contain** the OAuth token and so this method (and all dependent methods (e.g. for two factor)) will fail with `Malformed response` error.

I have done only a very brief testing so I *might* have missed something.

An easy test for anyone's bot account is logging to steamcommunity.com and trying to load the web chat. You will get "unauthorized error" if your account is (partially) limited.

**Comment by Smarrito** [comment]
As for the account limitations. It seems to be quite random for this bug to appear. I tried to auth one of my accounts yesterday and failed. Logged in via browser and had the "Havent bought anything in 30 days to a year" msg + "Acc is limited" on the SCM mainpage. 

However, I had just bought a game a week ago and my account was fully functional (Including friend adding and even Web Chat). 

Yesterday I read an answer to a similar issue from mckay, where he said that these limitations can happen quite random and from my own experience this is true. A couple months ago I had a sudden limitation on my Main Account, but only on a specific chrome profile on my work pc. Client and any other browser / chrome profile were perfectly fine. Thus, I got the feeling that it may be connected to some faulty cookie. 

Had no possibility to check this on my "freshly limited" account, since I only had an existing cookie in one chrome profile. If I clear that I would be limitated for 7 days anyways.

**Comment by s992** [comment]
I have an [open PR](https://github.com/DoctorMcKay/node-steamcommunity/pull/17) that resolves this issue. All of my bots were receiving "Malformed response", but I successfully enabled 2FA for all of them using my fork. It's not perfect (see McKay's comment), but it worked for me.

It will not work if you are logging in through another lib and using `setCookies`, though - it has to pose as the mobile client in order to receive the oAuth token on login.

**Comment by DoctorMcKay** [comment]
PR #17 will resolve this so long as you login through steamcommunity. There is no way to resolve this using external cookies as far as I know. 

All I can say is, send in a Steam support ticket and use SteamUser in the meantime. I already have support ticket in. Maybe if enough of us send one, at least one of us will get a human response.

**Comment by scholtzm** [comment]
Yeah I did not check the open PRs before submitting this issue. The fix is somewhat simpler than I expected.
