### ISSUE TITLE
[Enhancement] Add a method to see when CEconitem will be available to trade, if trade-locked

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steamcommunity#224]
This mainly would be needed in csgo items probably, but it also happens if you have bought that item recently in the market, so it would be pretty useful i think..

There is already a way to see if item is tradable or not, so it would be like an improvement to also see when it will be available to trade, if not.

**Comment by DoctorMcKay** [comment]
This was requested previously in #194 and was rejected because trade locks are implemented on a per-game basis; there's no global Steam mechanism for them. Even items that are trade locked because they were bought on the market are implemented per-game.

CEconItem is a game-agnostic interface, so unfortunately trade lock methods don't fit in it.

**Comment by JustAzul** [comment]
> Even items that are trade locked because they were bought on the market are implemented per-game.

I wasn't aware, nice to know though, ty!
