### ISSUE TITLE
Error while trying to login to get TOTP code eResult 11

### ISSUE THREAD

**Issue by myserywork** [DoctorMcKay/node-steamcommunity#57]
$ node index.js
Username: 
Password: 
An email has been sent to your address at gmail.com
Steam Guard Code: MK829
Logged on!
{ [Error: Error 11] eresult: 11 }

what is that anyone knwos how to fix it?

**Comment by DoctorMcKay** [comment]
Please direct future questions to the [Steam group](http://steamcommunity.com/groups/SteamRE/discussions/5/).

Error 11 is InvalidState, and usually happens when you try to enable two-factor authentication, but it's already enabled. From your snippet it looks like this isn't the case, so I don't really know. You'd probably have to ask Steam Support, or just try again later.

Also make sure you have a phone linked, but that should (used to, at least) result in a different error.
