### ISSUE TITLE
Edit announcement

### ISSUE THREAD

**Issue by demipixel** [DoctorMcKay/node-steamcommunity#69]
I see addAnnouncement... How can I edit one? Is this just stupid Demi not looking long enough at the documentation?

**Comment by LeCoffee** [comment]
From looking at the files in components/groups.js and classes/CSteamGroup.js this functionality is not implemented yet. I'm going to take a crack at adding it in a few hours, I'd like to contribute to this library.

**Comment by DoctorMcKay** [comment]
Right, this doesn't exist yet. If @LeCoffee sends a PR I'll accept it ASAP, but I'm a bit too busy to work on new features right now.

**Comment by LeCoffee** [comment]
#70 Apologies for the delay, I was out :p I've only tested to make sure it works haven't tried random scenarios where the announcement ID might be wrong.

Also to get the announcement ID you have to get it manually for now. I don't believe it is returned from anywhere although it could possibly be returned as the redirected URI from when creating an announcement.

@DoctorMcKay I will update the wiki when you pull my changes. Also I noticed for editing an announcement its very similar to the post announcement, I could probably simplify my code to work with your original method if you like, didn't want to touch your original stuff since I didn't really have much time to test.

**Comment by DoctorMcKay** [comment]
No need to apologize! 

If I remember correctly, posting a new announcement only redirects to the list of all the group's announcements. We would need to add a new method to parse that list if this is going to be 100% automated. 

In the meantime, what you contributed should be fine. I'll review and merge when I get home.

**Comment by LeCoffee** [comment]
Just tested, seems like you're right it redirects to the list of announcements. Maybe we could add a method to getAllAnnouncements or something. I recall using RSS at one point for getting announcements although I also saw a method which only gave you the content.

Just found it 
http://steamcommunity.com/groups/groupname/rss/ 

Will be much easier to use this rather than try parse through each page scraping HTML that could change IMO. I'll see if I can work on it in my fork when I get some time

**Comment by DoctorMcKay** [comment]
Well, I absolutely appreciate any and every contribution!

**Comment by LeCoffee** [comment]
Implemented with RSS. Only real downside I can see is that it only fetches the authors personaname and not SteamID. In the future this should probably be replaced or improved upon to get a detailed view of an announcement (e.g. call group.getAnnoncement(aid, callback) which goes to http://steamcommunity.com/groups/ group name /announcements/detail/aid and get the authors steamid and returns an object that has methods to upvote, downvote get comments and post comments, perhaps maybe even get its own CSteamGroupAnnouncement.js?)

**Comment by demipixel** [comment]
deleteAnnouncent too? :3

**Comment by LeCoffee** [comment]
Done :smile:

**Comment by DoctorMcKay** [comment]
#70 is live in v3.18.0.
