### ISSUE TITLE
Minor update to Method Comment

### ISSUE THREAD

**Issue by gsaqui** [DoctorMcKay/node-steamcommunity#80]
In file `https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/confirmations.js`
Line 168

I find this a bit confusing:
`This shouldn't be any less than 10,000 probably.` - does this mean it should be above 10k or below.

Can I suggest you change it to:
`The value should probably be above 10,000` or even better leave out the word `probably`.

Thank you for all the great work.

**Comment by andrewda** [comment]
> This shouldn't be any less than 10,000 probably.
> Should not be less than 10,000
> More than 10,000

This comment is fine in my opinion...

**Comment by gsaqui** [comment]
Sure the comment is correct but why I raised the issue was because it isn't as clear as it could be.  It took me a couple of minutes to make sure I had the correct value.  I was hoping one of the core developers agreed and made the quick update so that someone else in the future wouldn't be confused as I was.

**Comment by andrewda** [comment]
In my opinion, the current wording, `This shouldn't be any less than 10,000 probably`, makes more sense under the circumstances, because the comment is emphasizing that the values *should not* be below 10,000.

I see what you mean, though. Both wordings have their ups and downs. Maybe a longer explanation as to why the value should not be below 10,000 would be the best bet.

**Comment by DoctorMcKay** [comment]
^ Is that better?

**Comment by andrewda** [comment]
Yep, looks good to me!

**Comment by gsaqui** [comment]
Looks great - thank you.
